name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Installing python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Updating pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Testing with pytest
        run: |
          pip install pytest
          pytest
